name: Pytest

# Allows you to run this workflow manually from the Actions tab
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test_full_install:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.8]
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} for full install
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Full install wit Rasa 2
      run: |
        python -m pip install -U pip
        pip install pybind11==2.8.0
        pip install --progress-bar off -U ".[rasa2, spacy, watson, fasttext, luis, huggingface]"
        pip install pytest pytest-mock

    - name: Test full test suite
      run: pytest tests/ --ignore tests/test_watson_vendor.py

  test_rasa3:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.8]
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} for testing Rasa 3
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U ".[rasa3, huggingface]"
        pip install pytest pytest-mock

    - name: Test Rasa 3
      run: |
        pytest tests/test_vendors.py::test_rasa
        pytest tests/test_dataset_loaders.py
