name: Static Code Checks

on:
  push:
    # run on any branch
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]


jobs:
  checks:
    env:
      src: "nlubridge"
      other-src: "tests setup.py"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[develop]

    - name: Check with pydocstyle
      run: pydocstyle --count ${{ env.src }} ${{ env.other-src }}

    - name: Check with black
      run: black ${{ env.src }} ${{ env.other-src }} --check --diff

    - name: Check with flake8
      run: flake8 ${{ env.src }} ${{ env.other-src }}

    - name: Check with isort
      run: isort ${{ env.src }} ${{ env.other-src }} --check --diff

    - name: Check with mdformat
      run: mdformat --check *.md

    - name: Check with mypy
      run: mypy --ignore-missing-imports --install-types --non-interactive ${{ env.src }} ${{ env.other-src }}

    - name: Check with pylint
      run: pylint --fail-under 6 ${{ env.src }}
